const PROTOCOLS = [
  {
    id: "P1",
    code: "P.1",
    name: "CRÁNEO S/C",
    fullName: "TC sin Contraste I.V. de Cráneo",
    zona: "craneo",
    contraste: false,
    tags: ["cráneo", "cerebro", "sin contraste"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, cabeza hacia el gantry (headfirst). Inmovilizar cabeza con el soporte craneal." },
      { fase: "Centrado", icono: "center", texto: "Centrado en línea orbitomeatal. Láser lateral a nivel del CAE." },
      { fase: "Topograma", icono: "topo", texto: "Scout lateral de cráneo." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde base de cráneo hasta calota (caudo-craneal)." },
      { fase: "Adquisición", icono: "scan", texto: "Secuencial 2,5 × 2,5 mm. Caudo-craneal. NO se reconstruye al ser secuencial." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: null,
    reconstrucciones: "No aplica (secuencial).",
    notas: "No requiere reconstrucción por ser adquisición secuencial."
  },
  {
    id: "P2",
    code: "P.2",
    name: "CRÁNEO C/C",
    fullName: "TC con Contraste I.V. de Cráneo",
    zona: "craneo",
    contraste: true,
    tags: ["cráneo", "cerebro", "con contraste"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, cabeza hacia el gantry (headfirst). Inmovilizar cabeza con el soporte craneal." },
      { fase: "Centrado", icono: "center", texto: "Centrado en línea orbitomeatal. Láser lateral a nivel del CAE." },
      { fase: "Topograma", icono: "topo", texto: "Scout lateral de cráneo." },
      { fase: "Contraste", icono: "contrast", texto: "100 cc de yodo + 20-40 cc de suero. Velocidad: 3 cc/sg. Delay: 100 sg." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde base de cráneo hasta calota (caudo-craneal)." },
      { fase: "Adquisición", icono: "scan", texto: "Secuencial 2,5 × 2,5 mm. Caudo-craneal. NO se reconstruye al ser secuencial." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 20-40 cc suero", velocidad: "3 cc/sg", delay: "100 sg", bt: false },
    reconstrucciones: "No aplica (secuencial).",
    notas: "No requiere reconstrucción por ser adquisición secuencial."
  },
  {
    id: "P3",
    code: "P.3",
    name: "ANGIOTC CRÁNEO",
    fullName: "Angio-TC de Cráneo",
    zona: "craneo",
    contraste: true,
    tags: ["cráneo", "angio", "arterias", "venas", "angiotc"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, cabeza hacia el gantry (headfirst)." },
      { fase: "Centrado", icono: "center", texto: "Centrado en línea orbitomeatal." },
      { fase: "Topograma", icono: "topo", texto: "Scout lateral de cráneo." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en cayado aórtico. Umbral 140 HU con mínimo delay para arterias. Para venas: 20 sg de retraso sobre el bolus tracking." },
      { fase: "Contraste", icono: "contrast", texto: "80 cc de yodo + 40 cc de suero. Velocidad: 3 cc/sg." },
      { fase: "Nivel de corte", icono: "cut", texto: "Incluir todo el cráneo (caudo-craneal)." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 0,9 × 0,45 mm. Caudo-craneal." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: { volumen: "80 cc yodo + 40 cc suero", velocidad: "3 cc/sg", delay: "BT (mín. delay arterias / +20 sg venas)", bt: true, roi: "Cayado aórtico", umbral: "140 HU" },
    reconstrucciones: "No especificadas adicionales.",
    notas: "Para estudio venoso añadir 20 sg de retraso sobre el BT."
  },
  {
    id: "P3BIS",
    code: "P.3 BIS",
    name: "SENOS VENOSOS",
    fullName: "TC Cráneo S/C + Angio-TC Cráneo (Senos Venosos)",
    zona: "craneo",
    contraste: true,
    tags: ["senos venosos", "cráneo", "trombosis", "venoso"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, cabeza hacia el gantry (headfirst)." },
      { fase: "Fase 1: Cráneo S/C", icono: "scan", texto: "Primero: cráneo secuencial SIN contraste (igual que P.1)." },
      { fase: "Contraste", icono: "contrast", texto: "100 cc de yodo + 40 cc de suero. Delay: 50 sg. SIN bolus tracking." },
      { fase: "Nivel de corte", icono: "cut", texto: "Incluir cráneo entero: desde C2 hasta la calota." },
      { fase: "Fase 2: Cráneo C/C", icono: "scan", texto: "Helicoidal con contraste. Delay 50 sg. Desde C2 hasta calota." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 40 cc suero", velocidad: "No especificada", delay: "50 sg", bt: false },
    reconstrucciones: "No especificadas adicionales.",
    notas: "NO usar bolus tracking. Dos estudios consecutivos: secuencial s/c + helicoidal c/c."
  },
  {
    id: "P4",
    code: "P.4",
    name: "CUELLO DOBLE INYECCIÓN",
    fullName: "TC con Contraste I.V. de Cuello",
    zona: "cuello",
    contraste: true,
    tags: ["cuello", "doble inyección", "tiroides", "laringe"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, cabeza hacia el gantry. Hiperextensión suave del cuello. Brazos a lo largo del cuerpo." },
      { fase: "Centrado", icono: "center", texto: "Centrado a nivel del cuello, láser en línea media." },
      { fase: "Topograma", icono: "topo", texto: "Scout AP de cuello." },
      { fase: "Doble Inyección", icono: "contrast", texto: "1ª inyección: 70 cc contraste + 40 cc suero a 3 cc/sg. 2ª inyección: 30 cc yodo + 20 cc suero a 3 cc/sg. AMBAS SEGUIDAS SIN PAUSA, con 5 sg de retraso entre ellas." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde suelo de las órbitas hasta vértices pulmonares (cráneo-caudal)." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Cráneo-caudal. SIN bolus tracking. Se lanza a la vez que la bomba. Delay: 70 sg." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: { volumen: "70+30 cc yodo / 40+20 cc suero", velocidad: "3 cc/sg (ambas)", delay: "70 sg", bt: false },
    reconstrucciones: "No especificadas adicionales.",
    notas: "NO usar bolus tracking. Lanzar bomba y hélice simultáneamente."
  },
  {
    id: "P4BIS",
    code: "P.4 BIS",
    name: "CUELLO + TÓRAX DOBLE INYECCIÓN",
    fullName: "TC Cuello + TC Tórax (Doble Inyección)",
    zona: "cuello",
    contraste: true,
    tags: ["cuello", "tórax", "doble inyección"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino. Brazos ARRIBA para el tórax." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta descendente. BT activo." },
      { fase: "1ª Inyección", icono: "contrast", texto: "90 cc yodo + 20 cc suero a 3 cc/sg." },
      { fase: "Adquisición Tórax", icono: "scan", texto: "Hélice de TÓRAX con brazos hacia arriba." },
      { fase: "Bajada de brazos", icono: "position", texto: "Al terminar la hélice de tórax: indicar al paciente que BAJE LOS BRAZOS." },
      { fase: "2ª Inyección (MANUAL)", icono: "contrast", texto: "Lanzar manualmente: 30 cc contraste + 30 cc suero a 3 cc/sg." },
      { fase: "Adquisición Cuello", icono: "scan", texto: "Hélice de CUELLO. 20 sg de intervalo entre hélice de tórax y cuello (ya programados en el escáner)." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: { volumen: "90+30 cc yodo", velocidad: "3 cc/sg", delay: "BT aorta descendente + 20 sg entre hélices", bt: true, roi: "Aorta descendente" },
    reconstrucciones: "No especificadas.",
    notas: "⚠️ La 2ª inyección HAY QUE LANZARLA MANUALMENTE tras bajar los brazos del paciente."
  },
  {
    id: "P5",
    code: "P.5",
    name: "TSA + WILLIS",
    fullName: "Angio-TC Troncos Supraaórticos + Polígono de Willis",
    zona: "craneo",
    contraste: true,
    tags: ["troncos supraaórticos", "TSA", "willis", "carótidas", "angiotc"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, cabeza hacia el gantry." },
      { fase: "Topograma", icono: "topo", texto: "Scout lateral incluyendo cuello y cráneo." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en cayado aórtico. Umbral 120 HU." },
      { fase: "Contraste", icono: "contrast", texto: "70 cc de yodo + 40 cc de suero. Velocidad: 4 cc/sg." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde por debajo del cayado hasta la calota, incluyendo cráneo completo (caudo-craneal)." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Caudo-craneal." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: { volumen: "70 cc yodo + 40 cc suero", velocidad: "4 cc/sg", delay: "BT", bt: true, roi: "Cayado aórtico", umbral: "120 HU" },
    reconstrucciones: "No especificadas adicionales.",
    notas: "Estudio completo desde cayado hasta calota en una sola hélice."
  },
  {
    id: "P6",
    code: "P.6",
    name: "TÓRAX C/C",
    fullName: "TC con Contraste I.V. de Tórax",
    zona: "torax",
    contraste: true,
    tags: ["tórax", "pulmón", "mediastino", "con contraste"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry (feetfirst). Brazos ARRIBA (por encima de la cabeza)." },
      { fase: "Centrado", icono: "center", texto: "Centrado a nivel del manubrio esternal." },
      { fase: "Topograma", icono: "topo", texto: "Scout AP de tórax." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta descendente." },
      { fase: "Contraste", icono: "contrast", texto: "100 cc de yodo + 20 cc de suero. Velocidad: 3 cc/sg." },
      { fase: "Nivel de corte", icono: "cut", texto: "Tórax completo (cráneo-caudal)." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Cráneo-caudal." },
      { fase: "Reconstrucciones", icono: "recon", texto: "Axial y coronal 5×5 con ventana de mediastino. Axial y coronal 5×5 con ventana de pulmón y realce." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 20 cc suero", velocidad: "3 cc/sg", delay: "BT aorta descendente", bt: true, roi: "Aorta descendente" },
    reconstrucciones: "Axial+Coronal 5×5 mediastino; Axial+Coronal 5×5 pulmón+realce.",
    notas: "Brazos siempre arriba para tórax."
  },
  {
    id: "P7",
    code: "P.7",
    name: "TÓRAX ALTA RESOLUCIÓN",
    fullName: "TC de Alta Resolución de Tórax (TCAR/HRCT)",
    zona: "torax",
    contraste: false,
    tags: ["tórax", "alta resolución", "TCAR", "intersticio", "pulmón"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA." },
      { fase: "Centrado", icono: "center", texto: "Centrado a nivel del manubrio esternal." },
      { fase: "Topograma", icono: "topo", texto: "Scout AP de tórax." },
      { fase: "Contraste", icono: "contrast", texto: "⚠️ El radiólogo especificará si es sin o CON contraste. Si es c/c: igual que Protocolo 6." },
      { fase: "Nivel de corte", icono: "cut", texto: "Tórax completo (cráneo-caudal)." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Incluir todo el tórax." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: null,
    reconstrucciones: "Alta resolución — consultar con radiólogo.",
    notas: "Confirmar con radiólogo si requiere contraste antes de empezar."
  },
  {
    id: "P8",
    code: "P.8",
    name: "TORACOABDOMINAL C/C",
    fullName: "TC Tórax + Abdomen Superior con Contraste (Bifásico)",
    zona: "torax",
    contraste: true,
    tags: ["tórax", "abdomen", "hígado", "bifásico", "arterial", "portal"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA." },
      { fase: "Topograma", icono: "topo", texto: "Scout AP toracoabdominal." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta a la altura del hígado." },
      { fase: "Contraste", icono: "contrast", texto: "100 cc de yodo + 20 cc de suero. Velocidad: 3 cc/sg." },
      { fase: "Fase Arterial", icono: "scan", texto: "1ª hélice: tórax + abdomen superior (fase arterial)." },
      { fase: "Fase Portal", icono: "scan", texto: "2ª hélice: solo abdomen superior (fase portal)." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 20 cc suero", velocidad: "3 cc/sg", delay: "BT hígado", bt: true, roi: "Aorta a nivel del hígado" },
    reconstrucciones: "No especificadas adicionales.",
    notas: "Dos fases: arterial (tórax+abd sup) + portal (solo abd sup)."
  },
  {
    id: "P8_4",
    code: "P.8+4",
    name: "TÓRAX-ABD + CUELLO DOBLE INYECCIÓN",
    fullName: "TC Tórax-Abdomen Superior + TC Cuello (Doble Inyección)",
    zona: "torax",
    contraste: true,
    tags: ["tórax", "abdomen", "cuello", "doble inyección"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino. Brazos ARRIBA para tórax-abdomen." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta a la altura del hígado." },
      { fase: "1ª Inyección", icono: "contrast", texto: "90 cc yodo + 40 cc suero a 3 cc/sg." },
      { fase: "Fases Tórax-Abdomen", icono: "scan", texto: "Tórax-abd sup arterial + abd sup portal con brazos arriba." },
      { fase: "Bajada de brazos", icono: "position", texto: "Al terminar la fase portal: indicar al paciente que BAJE LOS BRAZOS." },
      { fase: "2ª Inyección (MANUAL)", icono: "contrast", texto: "Lanzar manualmente: 30 cc contraste + 30 cc suero a 3 cc/sg." },
      { fase: "Adquisición Cuello", icono: "scan", texto: "Hélice de cuello. 20 sg entre la fase portal y la del cuello (ya programados)." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: { volumen: "90+30 cc yodo", velocidad: "3 cc/sg", delay: "BT hígado + 20 sg entre fases", bt: true, roi: "Aorta nivel hígado" },
    reconstrucciones: "No especificadas.",
    notas: "⚠️ 2ª inyección MANUAL tras bajar brazos del paciente."
  },
  {
    id: "P9",
    code: "P.9",
    name: "TEP",
    fullName: "Angio-TC de Arteria Pulmonar Bilateral (TEP)",
    zona: "torax",
    contraste: true,
    tags: ["TEP", "tromboembolismo", "arteria pulmonar", "angio", "urgencias"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA." },
      { fase: "Instrucción respiratoria", icono: "info", texto: "Entrenar al paciente en apnea inspiratoria antes del estudio." },
      { fase: "Topograma", icono: "topo", texto: "Scout AP de tórax." },
      { fase: "Bolus Tracking", icono: "roi", texto: "Localizador en arterias pulmonares principales. ROI en tronco o ramas pulmonares. Umbral: 80 HU. Mínimo retraso posible." },
      { fase: "Contraste", icono: "contrast", texto: "50 cc de yodo + 50 cc de suero. Velocidad: 4,5 cc/sg." },
      { fase: "Nivel de corte", icono: "cut", texto: "Todo el tórax (cráneo-caudal)." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Cráneo-caudal." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: { volumen: "50 cc yodo + 50 cc suero", velocidad: "4,5 cc/sg", delay: "BT (mín. retraso)", bt: true, roi: "Tronco/ramas pulmonares", umbral: "80 HU" },
    reconstrucciones: "No especificadas.",
    notas: "Mínimo retraso posible tras umbral 80 HU. Apnea inspiratoria imprescindible."
  },
  {
    id: "P10_CS",
    code: "P.10",
    name: "CALCIO SCORE",
    fullName: "TC de Cuantificación de Calcio Coronario",
    zona: "torax",
    contraste: false,
    tags: ["calcio score", "coronarias", "cardíaco", "calcificación"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA. Colocar monitorización cardiaca (ECG)." },
      { fase: "Topograma", icono: "topo", texto: "Scout AP cardiaco." },
      { fase: "FOV", icono: "cut", texto: "FOV ajustado al corazón." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde ~2 cm por debajo del cayado hasta ~3 cm por debajo de la anatomía cardiaca." },
      { fase: "Adquisición", icono: "scan", texto: "Axial 2,5 mm cada 25 mm. Con monitorización cardiaca (ECG)." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: null,
    reconstrucciones: "No aplica.",
    notas: "Imprescindible monitorización cardiaca (ECG). Sin contraste I.V."
  },
  {
    id: "P10_AC",
    code: "P.10",
    name: "ANGIO CORONARIO",
    fullName: "Angio-TC de Arterias Coronarias",
    zona: "torax",
    contraste: true,
    tags: ["coronarias", "cardíaco", "angio", "bypass"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA. Monitorización cardiaca (ECG)." },
      { fase: "Topograma", icono: "topo", texto: "Scout AP. Comprobar programación en ambos planos." },
      { fase: "Bolus Tracking", icono: "roi", texto: "Localizador en carina. ROI en aorta descendente." },
      { fase: "Contraste", icono: "contrast", texto: "100 cc de yodo + 40 cc de suero. Velocidad: 5 cc/sg." },
      { fase: "Nivel de corte Coronarias", icono: "cut", texto: "0,9 × 0,45 mm. Mismo rango que el calcio coronario." },
      { fase: "Nivel de corte Bypass", icono: "cut", texto: "Desde región supraclavicular hasta ~3 cm por debajo de la anatomía cardiaca." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 0,9 × 0,45 mm con ECG. Comprobar programación en ambos planos." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 40 cc suero", velocidad: "5 cc/sg", delay: "BT", bt: true, roi: "Aorta descendente (localizador en carina)" },
    reconstrucciones: "No especificadas.",
    notas: "Monitorización ECG imprescindible. Comprobar programación en 2 planos."
  },
  {
    id: "P11_completa",
    code: "P.11",
    name: "ANGIOTC AORTA COMPLETA",
    fullName: "Angio-TC de Arteria Aorta Completa",
    zona: "abdomen",
    contraste: true,
    tags: ["aorta", "angio", "disección", "aneurisma"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA." },
      { fase: "Topograma", icono: "topo", texto: "Scout AP toracoabdominopélvico." },
      { fase: "Fase S/C (si indicado)", icono: "scan", texto: "Solo si lo indica el radiólogo: estudio sin contraste previo con el mismo rango." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta torácica distal. Umbral 140 HU, mínimo retraso." },
      { fase: "Contraste", icono: "contrast", texto: "100 cc de yodo + 40 cc de suero. Velocidad: 4 - 4,5 cc/sg." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde 2 cm por encima del cayado aórtico hasta la sínfisis del pubis." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 2 × 1 mm." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 40 cc suero", velocidad: "4-4,5 cc/sg", delay: "BT (140 HU, mín. retraso)", bt: true, roi: "Aorta torácica distal", umbral: "140 HU" },
    reconstrucciones: "No especificadas.",
    notas: "Fase S/C previa solo si lo indica el radiólogo."
  },
  {
    id: "P11_tor",
    code: "P.11",
    name: "ANGIOTC AORTA TORÁCICA",
    fullName: "Angio-TC de Arteria Aorta Torácica",
    zona: "torax",
    contraste: true,
    tags: ["aorta torácica", "angio", "disección"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, brazos ARRIBA." },
      { fase: "Fase S/C (si indicado)", icono: "scan", texto: "Solo si indica el radiólogo: estudio s/c previo." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta descendente. Umbral 140 HU, mínimo retraso." },
      { fase: "Contraste", icono: "contrast", texto: "100 cc yodo + 40 cc suero. Velocidad: 4 - 4,5 cc/sg." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde 2 cm por encima del cayado hasta bases pulmonares." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 2 × 1 mm." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 40 cc suero", velocidad: "4-4,5 cc/sg", delay: "BT aorta descendente (140 HU)", bt: true, roi: "Aorta descendente", umbral: "140 HU" },
    reconstrucciones: "No especificadas.",
    notas: ""
  },
  {
    id: "P11_abd",
    code: "P.11",
    name: "ANGIOTC AORTA ABDOMINAL",
    fullName: "Angio-TC de Arteria Aorta Abdominal y Bifurcación Ilíaca",
    zona: "abdomen",
    contraste: true,
    tags: ["aorta abdominal", "angio", "ilíacas", "urgencias"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, brazos ARRIBA." },
      { fase: "Fase S/C (urgencias)", icono: "scan", texto: "En urgencias: estudio s/c previo con mismo rango." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta descendente por encima de hígado. Umbral 140 HU, mínimo retraso." },
      { fase: "Contraste", icono: "contrast", texto: "100 cc yodo + 40 cc suero. Velocidad: 4 - 4,5 cc/sg." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde bases pulmonares hasta sínfisis del pubis." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 2 × 1 mm." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 40 cc suero", velocidad: "4-4,5 cc/sg", delay: "BT aorta descendente (140 HU)", bt: true, roi: "Aorta descendente por encima de hígado", umbral: "140 HU" },
    reconstrucciones: "No especificadas.",
    notas: "En urgencias: siempre hacer fase s/c previa."
  },
  {
    id: "P12",
    code: "P.12",
    name: "ANGIOTC ARTERIAS ABDOMINALES",
    fullName: "Angio-TC de Abdomen y Pelvis",
    zona: "abdomen",
    contraste: true,
    tags: ["abdomen", "pelvis", "arterias abdominales", "angio"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, brazos ARRIBA." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta descendente por encima de hígado." },
      { fase: "Contraste", icono: "contrast", texto: "80 cc yodo + 40 cc suero. Velocidad: 4 - 4,5 cc/sg." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde bases pulmonares hasta sínfisis del pubis." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: { volumen: "80 cc yodo + 40 cc suero", velocidad: "4-4,5 cc/sg", delay: "BT aorta descendente", bt: true, roi: "Aorta descendente por encima de hígado" },
    reconstrucciones: "No especificadas.",
    notas: ""
  },
  {
    id: "P13",
    code: "P.13",
    name: "ANGIOTC MM.II.",
    fullName: "Angio-TC de Miembro Inferior Bilateral",
    zona: "extremidades",
    contraste: true,
    tags: ["miembros inferiores", "piernas", "arterial", "isquemia"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Pies juntos y en ligera rotación interna." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta descendente por encima de hígado." },
      { fase: "Contraste", icono: "contrast", texto: "130 cc yodo (para ~70 kg) + 40 cc suero. Velocidad: 4,5 cc/sg." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde por encima de los riñones hasta la punta de los pies (hélice única)." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 2 × 1 mm. Única hélice de cabeza a pies." },
      { fase: "Envío", icono: "send", texto: "Todas las series a la estación 1. Scout, datos crudos y dosis al Carestream." }
    ],
    contraste_detalle: { volumen: "130 cc yodo + 40 cc suero", velocidad: "4,5 cc/sg", delay: "BT aorta descendente", bt: true, roi: "Aorta descendente por encima de hígado" },
    reconstrucciones: "No especificadas.",
    notas: "Ajustar volumen de contraste según peso del paciente (~130 cc para 70 kg)."
  },
  {
    id: "P14",
    code: "P.14",
    name: "TC ENTEROCLISIS",
    fullName: "Enteroclisis-TC",
    zona: "abdomen",
    contraste: true,
    tags: ["intestino delgado", "enteroclisis", "intestino"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Preparación oral", icono: "info", texto: "1500 cc de solución al 3% de sorbitol. Administrar 300 cc en dosis: 1ª 45 min antes, después a los 30, 20 y 10 min. Última dosis con el paciente en mesa justo antes (0 sg)." },
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA." },
      { fase: "Contraste IV", icono: "contrast", texto: "100 cc yodo + 40 cc suero. Velocidad: 3 cc/sg. Delay: 60 sg." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde cúpulas diafragmáticas hasta sínfisis del pubis." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 40 cc suero", velocidad: "3 cc/sg", delay: "60 sg", bt: false },
    reconstrucciones: "No especificadas.",
    notas: "Protocolo de contraste oral específico con sorbitol. Coordinar tiempos de ingesta."
  },
  {
    id: "P15",
    code: "P.15",
    name: "COLONOSCOPIA VIRTUAL",
    fullName: "Endoscopia Virtual de Colon con TC",
    zona: "abdomen",
    contraste: false,
    tags: ["colon", "colonoscopia virtual", "pólipos", "baja dosis"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Preparación", icono: "info", texto: "Introducir máxima cantidad de aire tolerable por el paciente mediante sonda rectal." },
      { fase: "Posición 1: Prono", icono: "position", texto: "1ª adquisición: DECÚBITO PRONO, pies hacia el gantry." },
      { fase: "Adquisición Prono", icono: "scan", texto: "Helicoidal 1,5 × 0,75 mm. Baja dosis: 120 kV / 100 mAs. Desde cúpulas diafragmáticas hasta sínfisis del pubis." },
      { fase: "Reinsuflar si precisa", icono: "info", texto: "Entre adquisiciones: introducir más aire si fuera necesario." },
      { fase: "Posición 2: Supino", icono: "position", texto: "2ª adquisición: DECÚBITO SUPINO, mismo rango." },
      { fase: "Adquisición Supino", icono: "scan", texto: "Mismos parámetros. Sin contraste I.V." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: null,
    reconstrucciones: "No especificadas.",
    notas: "Baja dosis (120 kV/100 mAs). Sin contraste I.V. Dos posiciones: prono + supino."
  },
  {
    id: "P16_cc",
    code: "P.16",
    name: "ABDOMEN Y PELVIS C/C",
    fullName: "TC con Contraste I.V. de Abdomen y Pelvis (Fase Portal)",
    zona: "abdomen",
    contraste: true,
    tags: ["abdomen", "pelvis", "portal", "con contraste"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta a nivel del hígado." },
      { fase: "Contraste IV", icono: "contrast", texto: "100 cc yodo + 20 cc suero. Velocidad: 3 cc/sg." },
      { fase: "Nivel de corte", icono: "cut", texto: "Abdomen y pelvis completos (única fase)." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Una única fase abdominopélvica." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 20 cc suero", velocidad: "3 cc/sg", delay: "BT hígado", bt: true, roi: "Aorta nivel hígado" },
    reconstrucciones: "No especificadas.",
    notas: ""
  },
  {
    id: "P16_sc",
    code: "P.16",
    name: "ABDOMEN Y PELVIS S/C",
    fullName: "TC sin Contraste I.V. de Abdomen y Pelvis",
    zona: "abdomen",
    contraste: false,
    tags: ["abdomen", "pelvis", "sin contraste", "cólico", "litiasis"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA." },
      { fase: "Topograma", icono: "topo", texto: "Scout AP abdominopélvico." },
      { fase: "Nivel de corte", icono: "cut", texto: "Abdomen y pelvis completos." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Única fase abdominopélvica." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: null,
    reconstrucciones: "No especificadas.",
    notas: ""
  },
  {
    id: "P17",
    code: "P.17",
    name: "HÍGADO TRIFÁSICO",
    fullName: "TC Dinámica con Contraste de Hígado (Trifásico)",
    zona: "abdomen",
    contraste: true,
    tags: ["hígado", "trifásico", "HCC", "arterial", "venoso", "tardío"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta a nivel del hígado." },
      { fase: "Contraste", icono: "contrast", texto: "100 cc yodo + 20 cc suero. Velocidad: 4 - 4,5 cc/sg." },
      { fase: "Fase 1: Sin contraste", icono: "scan", texto: "Abdomen superior S/C (solo hígado)." },
      { fase: "Fase 2: Arterial", icono: "scan", texto: "Abdomen superior en fase arterial." },
      { fase: "Fase 3: Venosa", icono: "scan", texto: "Abdomen superior en fase venosa." },
      { fase: "Fase 4: Tardía", icono: "scan", texto: "Abdomen superior en fase tardía." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 20 cc suero", velocidad: "4-4,5 cc/sg", delay: "BT hígado", bt: true, roi: "Aorta nivel hígado" },
    reconstrucciones: "No especificadas.",
    notas: "4 fases: previa s/c + arterial + venosa + tardía."
  },
  {
    id: "P18",
    code: "P.18",
    name: "ABDOMEN Y PELVIS ARTERIAL+PORTAL",
    fullName: "TC Abdomen y Pelvis con Contraste (Arterial + Portal)",
    zona: "abdomen",
    contraste: true,
    tags: ["abdomen", "pelvis", "bifásico", "arterial", "portal"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta a nivel del hígado." },
      { fase: "Contraste", icono: "contrast", texto: "100 cc yodo + 20 cc suero. Velocidad: 3 cc/sg." },
      { fase: "Fase Arterial", icono: "scan", texto: "1ª hélice: abdomen superior (fase arterial)." },
      { fase: "Fase Portal", icono: "scan", texto: "2ª hélice: abdomen + pelvis (fase portal)." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 20 cc suero", velocidad: "3 cc/sg", delay: "BT hígado", bt: true, roi: "Aorta nivel hígado" },
    reconstrucciones: "No especificadas.",
    notas: "Dos fases: arterial (abd sup) + portal (abd+pelvis)."
  },
  {
    id: "P19",
    code: "P.19",
    name: "UroTC",
    fullName: "Uro-TC (Urotomografía)",
    zona: "abdomen",
    contraste: true,
    tags: ["uro", "vía urinaria", "riñón", "uréter", "vejiga", "urotc"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA." },
      { fase: "Fase 1: S/C", icono: "scan", texto: "Adquisición sin contraste de abdomen y pelvis. SIN conectar la bomba." },
      { fase: "1ª Inyección", icono: "contrast", texto: "Conectar bomba: 80 cc contraste + 50 cc suero a 3 cc/sg." },
      { fase: "Espera", icono: "info", texto: "⏱️ Esperar 10 MINUTOS tras la 1ª inyección." },
      { fase: "2ª Inyección", icono: "contrast", texto: "70 cc contraste + 30 cc suero a 3 cc/sg. Lanzar hélice con 60 sg de delay." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Fase con contraste de abdomen y pelvis en decúbito supino." },
      { fase: "Aviso al paciente", icono: "info", texto: "⚠️ Cuando falten 20 segundos: pedir al paciente que tosa 2 veces con el abdomen." },
      { fase: "Envío", icono: "send", texto: "Las imágenes se envían automáticamente al Carestream." }
    ],
    contraste_detalle: { volumen: "80+70 cc yodo / 50+30 cc suero", velocidad: "3 cc/sg (ambas)", delay: "Fase 2: 60 sg tras 10 min espera", bt: false },
    reconstrucciones: "No especificadas.",
    notas: "⚠️ Esperar obligatoriamente 10 min entre 1ª y 2ª inyección. Pedir 2 toses abdominales cuando falten 20 sg."
  },
  {
    id: "P20",
    code: "P.20",
    name: "QUISTE RENAL",
    fullName: "TC de Quiste Renal (S/C + C/C Renal)",
    zona: "abdomen",
    contraste: true,
    tags: ["riñón", "quiste renal", "renal", "Bosniak"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA." },
      { fase: "Fase 1: S/C", icono: "scan", texto: "Fase sin contraste abarcando solo los riñones." },
      { fase: "Contraste", icono: "contrast", texto: "100 cc yodo + 20 cc suero. Velocidad: 3 cc/sg. Retraso: 90 sg." },
      { fase: "Fase 2: C/C", icono: "scan", texto: "Fase con contraste. Mismo rango: solo riñones." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Dos fases sobre riñones únicamente." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 20 cc suero", velocidad: "3 cc/sg", delay: "90 sg", bt: false },
    reconstrucciones: "No especificadas.",
    notas: "Rango limitado a riñones."
  },
  {
    id: "P21",
    code: "P.21",
    name: "CORPORAL LINFOMA",
    fullName: "TC Corporal para Linfoma (Cuello-Tórax-Abdomen-Pelvis)",
    zona: "corporal",
    contraste: true,
    tags: ["linfoma", "corporal", "estadificación", "cuello", "tórax", "abdomen"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, cabeza hacia el gantry. Brazos ARRIBA." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta descendente." },
      { fase: "Contraste", icono: "contrast", texto: "100 cc yodo + 20 cc suero. Velocidad: 3 cc/sg." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde suelo de las órbitas hasta sínfisis del pubis (única hélice)." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Única hélice suelo órbitas → sínfisis del pubis." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 20 cc suero", velocidad: "3 cc/sg", delay: "BT aorta descendente", bt: true, roi: "Aorta descendente" },
    reconstrucciones: "No especificadas.",
    notas: "Brazos ARRIBA. Hélice única de suelo de órbitas a sínfisis."
  },
  {
    id: "P22",
    code: "P.22",
    name: "CORPORAL NEOPLASIA",
    fullName: "TC Corporal para Neoplasia (Tórax-Abdomen-Pelvis Bifásico)",
    zona: "corporal",
    contraste: true,
    tags: ["neoplasia", "corporal", "estadificación", "tórax", "abdomen", "bifásico"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta a nivel del hígado." },
      { fase: "Contraste", icono: "contrast", texto: "100 cc yodo + 20 cc suero. Velocidad: 3 cc/sg." },
      { fase: "Fase Arterial", icono: "scan", texto: "1ª hélice: tórax + abdomen superior (fase arterial)." },
      { fase: "Fase Portal", icono: "scan", texto: "2ª hélice: abdomen + pelvis (fase portal)." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: { volumen: "100 cc yodo + 20 cc suero", velocidad: "3 cc/sg", delay: "BT hígado", bt: true, roi: "Aorta nivel hígado" },
    reconstrucciones: "No especificadas.",
    notas: "Dos fases: arterial (tórax+abd sup) + portal (abd+pelvis)."
  },
  {
    id: "P22_4",
    code: "P.22+4",
    name: "CORPORAL NEOPLASIA + CUELLO",
    fullName: "TC Corporal Neoplasia + Cuello (Doble Inyección)",
    zona: "corporal",
    contraste: true,
    tags: ["neoplasia", "corporal", "cuello", "doble inyección", "estadificación"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino. Brazos ARRIBA para tórax-abdomen." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta a la altura del hígado." },
      { fase: "1ª Inyección", icono: "contrast", texto: "100 cc yodo + 40 cc suero a 3 cc/sg." },
      { fase: "Fases Corporal", icono: "scan", texto: "Tórax-abd sup arterial + abd-pelvis portal con brazos arriba." },
      { fase: "Bajada de brazos", icono: "position", texto: "Al terminar fase portal: BAJAR BRAZOS del paciente." },
      { fase: "2ª Inyección (MANUAL)", icono: "contrast", texto: "Lanzar manualmente: 30 cc contraste + 30 cc suero a 3 cc/sg." },
      { fase: "Adquisición Cuello", icono: "scan", texto: "Hélice de cuello. 20 sg entre fase portal y cuello (ya programados)." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: { volumen: "100+30 cc yodo", velocidad: "3 cc/sg", delay: "BT hígado + 20 sg entre fases", bt: true, roi: "Aorta nivel hígado" },
    reconstrucciones: "No especificadas.",
    notas: "⚠️ 2ª inyección MANUAL tras bajar brazos. 20 sg entre fase portal y cuello preprogramados."
  },
  {
    id: "P23",
    code: "P.23",
    name: "CORPORAL POLITRAUMA",
    fullName: "TC Corporal de Politrauma",
    zona: "corporal",
    contraste: true,
    tags: ["politrauma", "urgencias", "trauma", "corporal"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino. Brazos ARRIBA si es posible." },
      { fase: "Parte 1: Cráneo S/C", icono: "scan", texto: "TC de cráneo SIN contraste (secuencial)." },
      { fase: "Parte 2: Columna Cervical", icono: "scan", texto: "TC de columna cervical S/C." },
      { fase: "Bolus Tracking", icono: "roi", texto: "ROI en aorta descendente. 120 cc yodo + 20 cc suero a 3 cc/sg." },
      { fase: "Parte 3: Tórax-Abdomen-Pelvis", icono: "scan", texto: "Helicoidal tórax + abdomen + pelvis c/c. Brazos arriba si es posible. 1 × 0,5 mm." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: { volumen: "120 cc yodo + 20 cc suero", velocidad: "3 cc/sg", delay: "BT aorta descendente", bt: true, roi: "Aorta descendente" },
    reconstrucciones: "No especificadas.",
    notas: "⚠️ Estudio en 3 partes. Cráneo → Col. cervical → Tx-Abd-Pv."
  },
  {
    id: "P24",
    code: "P.24",
    name: "OÍDO / PEÑASCO",
    fullName: "TC sin Contraste de Peñasco Bilateral",
    zona: "craneo",
    contraste: false,
    tags: ["oído", "peñasco", "hueso temporal", "otología"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, cabeza hacia el gantry. Inmovilización craneal máxima." },
      { fase: "Topograma", icono: "topo", texto: "Scout lateral y AP de base de cráneo." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde base del cráneo hasta cortar todo el peñasco (bilateral)." },
      { fase: "Adquisición", icono: "scan", texto: "0,67 × 0,33 mm. Resolución ULTRA ALTA. Filtro D (Bone)." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: null,
    reconstrucciones: "Resolución ultra alta con filtro Bone.",
    notas: "Máxima resolución. Filtro D (Bone). Inmovilización craneal imprescindible."
  },
  {
    id: "P25",
    code: "P.25",
    name: "SENOS PARANASALES",
    fullName: "TC sin Contraste de Senos Paranasales",
    zona: "craneo",
    contraste: false,
    tags: ["senos paranasales", "nariz", "sinusitis", "ORL"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, cabeza hacia el gantry. Cabeza en hiperextensión suave o neutra según indicación." },
      { fase: "Topograma", icono: "topo", texto: "Scout lateral de cara." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde maxilar inferior hasta final de senos frontales." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 0,9 × 0,45 mm. Filtro D (Bone)." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: null,
    reconstrucciones: "Filtro D (Bone).",
    notas: "Filtro Bone. Sin contraste."
  },
  {
    id: "P26",
    code: "P.26",
    name: "MACIZO FACIAL",
    fullName: "TC sin Contraste de Cara/Macizo Facial",
    zona: "craneo",
    contraste: false,
    tags: ["cara", "macizo facial", "traumatismo facial", "órbitas"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, cabeza hacia el gantry. Igual que senos paranasales." },
      { fase: "Adquisición", icono: "scan", texto: "Igual que P.25 (0,9 × 0,45 mm, filtro Bone)." },
      { fase: "Reconstrucciones", icono: "recon", texto: "Axial, coronal y sagital 3×3 en ventana de hueso." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream. ⚠️ Las reconstrucciones se mandan MANUALMENTE." }
    ],
    contraste_detalle: null,
    reconstrucciones: "Axial + Coronal + Sagital 3×3 ventana hueso. Enviar manualmente.",
    notas: "Las reconstrucciones NO se envían automáticamente — enviar manualmente."
  },
  {
    id: "P27_pelvis",
    code: "P.27",
    name: "PELVIS",
    fullName: "TC sin Contraste de Pelvis",
    zona: "abdomen",
    contraste: false,
    tags: ["pelvis", "cadera", "fractura", "traumatismo"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Abarcar zona de interés." },
      { fase: "Reconstrucciones", icono: "recon", texto: "Axial, sagital y coronal 3×3 en ventana de hueso." },
      { fase: "Envío", icono: "send", texto: "Automático al Carestream. ⚠️ Reconstrucciones se envían MANUALMENTE." }
    ],
    contraste_detalle: null,
    reconstrucciones: "Axial + Sagital + Coronal 3×3 ventana hueso. Enviar manualmente.",
    notas: "Reconstrucciones manuales."
  },
  {
    id: "P27_cadera",
    code: "P.27",
    name: "CADERA/S",
    fullName: "TC sin Contraste de Cadera Bilateral",
    zona: "extremidades",
    contraste: false,
    tags: ["cadera", "bilateral", "fractura", "prótesis"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Abarcar zona de interés." },
      { fase: "Reconstrucciones", icono: "recon", texto: "Axial, sagital y coronal 3×3 en ventana de hueso." },
      { fase: "Envío", icono: "send", texto: "Todas las series a estación 1. Scout, datos crudos y dosis al Carestream. ⚠️ Reconstrucciones MANUAL." }
    ],
    contraste_detalle: null,
    reconstrucciones: "Axial + Sagital + Coronal 3×3 hueso. Manual.",
    notas: "Reconstrucciones manuales. Todas las series a estación 1."
  },
  {
    id: "P28_cerv",
    code: "P.28",
    name: "COLUMNA CERVICAL",
    fullName: "TC sin Contraste de Columna Cervical",
    zona: "columna",
    contraste: false,
    tags: ["columna cervical", "vértebras cervicales", "cervical"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, cabeza hacia el gantry. Cuello en posición neutra." },
      { fase: "Topograma", icono: "topo", texto: "Scout lateral de columna cervical." },
      { fase: "Nivel de corte", icono: "cut", texto: "Según orientación clínica o indicación del radiólogo." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm." },
      { fase: "Reconstrucciones", icono: "recon", texto: "Axiales, sagitales y coronales 3×3 en ventana de hueso." },
      { fase: "Envío", icono: "send", texto: "Automático al Carestream. ⚠️ Reconstrucciones MANUALES." }
    ],
    contraste_detalle: null,
    reconstrucciones: "Axial + Sagital + Coronal 3×3 hueso. Manual.",
    notas: "Reconstrucciones manuales."
  },
  {
    id: "P28_dor",
    code: "P.28",
    name: "COLUMNA DORSAL",
    fullName: "TC sin Contraste de Columna Dorsal",
    zona: "columna",
    contraste: false,
    tags: ["columna dorsal", "columna torácica", "vértebras dorsales"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Brazos ARRIBA." },
      { fase: "Topograma", icono: "topo", texto: "Scout lateral de columna dorsal." },
      { fase: "Nivel de corte", icono: "cut", texto: "Según orientación clínica o indicación del radiólogo." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm." },
      { fase: "Reconstrucciones", icono: "recon", texto: "Axiales, sagitales y coronales 3×3 en ventana de hueso." },
      { fase: "Envío", icono: "send", texto: "Automático al Carestream. ⚠️ Reconstrucciones MANUALES." }
    ],
    contraste_detalle: null,
    reconstrucciones: "Axial + Sagital + Coronal 3×3 hueso. Manual.",
    notas: "Reconstrucciones manuales."
  },
  {
    id: "P28_lum",
    code: "P.28",
    name: "COLUMNA LUMBAR",
    fullName: "TC sin Contraste de Columna Lumbar",
    zona: "columna",
    contraste: false,
    tags: ["columna lumbar", "lumbosacra", "lumbar", "hernia discal"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Rodillas ligeramente flexionadas (apoyo bajo rodillas)." },
      { fase: "Topograma", icono: "topo", texto: "Scout lateral de columna lumbar." },
      { fase: "Nivel de corte", icono: "cut", texto: "Según orientación clínica o indicación del radiólogo." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm." },
      { fase: "Reconstrucciones", icono: "recon", texto: "Axiales, sagitales y coronales 3×3 en ventana de hueso." },
      { fase: "Envío", icono: "send", texto: "Automático al Carestream. ⚠️ Reconstrucciones MANUALES." }
    ],
    contraste_detalle: null,
    reconstrucciones: "Axial + Sagital + Coronal 3×3 hueso. Manual.",
    notas: "Reconstrucciones manuales."
  },
  {
    id: "P29",
    code: "P.29",
    name: "EXTREMIDADES",
    fullName: "TC sin Contraste de Extremidades (Pie, Tobillo, Muñeca, Codo)",
    zona: "extremidades",
    contraste: false,
    tags: ["extremidades", "pie", "tobillo", "muñeca", "codo", "fractura"],
    posicion: "variable",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Variable según extremidad. Protocolos específicos para pie D/I, tobillo D/I, muñeca D/I y codo D/I en PDI." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Abarcar zona de interés." },
      { fase: "Reconstrucciones", icono: "recon", texto: "Axial, sagital y coronal 3 mm siempre. 3D opcionalmente si lo prescribe el radiólogo." },
      { fase: "Envío", icono: "send", texto: "Automático al Carestream. ⚠️ Reconstrucciones MANUALES." }
    ],
    contraste_detalle: null,
    reconstrucciones: "Axial + Sagital + Coronal 3 mm. 3D si prescrito. Manual.",
    notas: "Seleccionar el protocolo correcto en PDI según extremidad y lateralidad."
  },
  {
    id: "P30",
    code: "P.30",
    name: "ART. SACROILÍACAS",
    fullName: "TC sin Contraste de Articulaciones Sacroilíacas",
    zona: "abdomen",
    contraste: false,
    tags: ["sacroilíacas", "sacro", "espondiloartritis", "pelvis"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry." },
      { fase: "Nivel de corte", icono: "cut", texto: "Desde crestas ilíacas hasta sínfisis del pubis." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm." },
      { fase: "Reconstrucciones", icono: "recon", texto: "Axial 3×3. Para-axial y para-coronal de 3 mm respecto al eje del sacro." },
      { fase: "Envío", icono: "send", texto: "Automático al Carestream. ⚠️ Reconstrucciones MANUALES." }
    ],
    contraste_detalle: null,
    reconstrucciones: "Axial 3×3 + Para-axial 3 mm + Para-coronal 3 mm (eje sacro). Manual.",
    notas: "Reconstrucciones oblicuas siguiendo eje del sacro. Manuales."
  },
  {
    id: "P31",
    code: "P.31",
    name: "FEMOROPATELAR",
    fullName: "TC Femoropatelar Bilateral (Relajación + Contracción + Flexión)",
    zona: "extremidades",
    contraste: false,
    tags: ["rótula", "rodilla", "femoropatelar", "TA-GT", "ángulo"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Posición General", icono: "position", texto: "Decúbito supino, pies hacia el gantry. Piernas extendidas, pies en rotación externa 15º." },
      { fase: "Fase 1: Relajación", icono: "scan", texto: "Piernas extendidas, pies rot. externa 15º. RELAJACIÓN muscular. Helicoidal. Incluir rótula completa e inserción lig. rotuliano en espina tibial." },
      { fase: "Fase 2: Contracción", icono: "scan", texto: "Misma posición (ext. + rot. ext. 15º). Paciente en CONTRACCIÓN del cuádriceps. Mismo rango." },
      { fase: "Fase 3: Flexión 20º", icono: "scan", texto: "Rodillas en FLEXIÓN de 20º, pies en rot. externa 15º. Mismo rango." },
      { fase: "Reconstrucciones", icono: "recon", texto: "Axial 3×3 de las 3 fases. Sagital 3×3 de la fase en flexión." },
      { fase: "Medidas especiales", icono: "recon", texto: "TA-GT: combinar imagen de tuberos. anterior tibia + imagen cóndilos femorales/garganta troclear (fase relajación). Ángulo femoropatelar: fase flexión (cóndilos+garganta + axial rótula mayor tamaño). Báscula: ambas fases extensión. Ángulo congruencia: fase flexión." },
      { fase: "Envío", icono: "send", texto: "Automático al Carestream. ⚠️ Reconstrucciones MANUALES." }
    ],
    contraste_detalle: null,
    reconstrucciones: "Axial 3×3 (3 fases) + Sagital 3×3 (flexión) + medidas TA-GT, ángulos. Manual.",
    notas: "3 adquisiciones. Ver instrucciones de superposición de imágenes en el protocolo."
  },
  {
    id: "P32",
    code: "P.32",
    name: "HOMBRO",
    fullName: "TC sin Contraste de Hombro (D, I o Bilateral)",
    zona: "extremidades",
    contraste: false,
    tags: ["hombro", "glenoide", "acromion", "fractura", "hombro"],
    posicion: "supino",
    entrada: "cabeza",
    steps: [
      { fase: "Posición", icono: "position", texto: "Decúbito supino, cabeza hacia el gantry. Brazo en posición anatómica a lo largo del cuerpo. Protocolos diferenciados para D e I en PDI." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 0,9 × 0,45 mm. Abarcar zona de interés." },
      { fase: "Reconstrucciones", icono: "recon", texto: "Axial, sagital y coronal siguiendo los ejes del hombro en ventana de hueso." },
      { fase: "Envío", icono: "send", texto: "Automático al Carestream. ⚠️ Reconstrucciones MANUALES." }
    ],
    contraste_detalle: null,
    reconstrucciones: "Axial + Sagital + Coronal (ejes del hombro) ventana hueso. Manual.",
    notas: "Usar protocolo específico D o I en PDI. Reconstrucciones siguiendo ejes anatómicos del hombro."
  },
  {
    id: "P33",
    code: "P.33",
    name: "CISTOTC",
    fullName: "Cistografía-TC",
    zona: "abdomen",
    contraste: true,
    tags: ["vejiga", "cistografía", "cistotc", "rotura vejiga"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Preparación", icono: "info", texto: "Diluir 5 ml de Visipaque en 250 ml de suero. Introducir en vejiga a través de la sonda vesical mediante sistema de suero." },
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry." },
      { fase: "Fase 1: Pelvis S/C", icono: "scan", texto: "Adquisición de pelvis SIN contraste." },
      { fase: "Fase 2: Pelvis C/C", icono: "scan", texto: "Adquisición de pelvis CON contraste (a través de sonda vesical)." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: { volumen: "5 ml Visipaque en 250 ml suero (intravesical)", velocidad: "Gravedad/manual", delay: "No aplica", bt: false },
    reconstrucciones: "No especificadas.",
    notas: "Contraste INTRAVESICAL por sonda. No IV. Dos fases pélvicas: s/c + c/c."
  },
  {
    id: "P34",
    code: "P.34",
    name: "ENEMA-TC",
    fullName: "TC de Colon con Bario (Enema-TC)",
    zona: "abdomen",
    contraste: false,
    tags: ["colon", "enema", "bario", "recto"],
    posicion: "supino",
    entrada: "pies",
    steps: [
      { fase: "Preparación", icono: "info", texto: "Preparación previa según protocolo de colon. Administrar enema de bario por vía rectal antes de la adquisición." },
      { fase: "Posición", icono: "position", texto: "Decúbito supino, pies hacia el gantry." },
      { fase: "Nivel de corte", icono: "cut", texto: "Fase abdominopélvica única." },
      { fase: "Adquisición", icono: "scan", texto: "Helicoidal 1 × 0,5 mm. Única fase abdominopélvica." },
      { fase: "Envío", icono: "send", texto: "Envío automático al Carestream." }
    ],
    contraste_detalle: null,
    reconstrucciones: "No especificadas.",
    notas: "Contraste de bario por vía rectal. Sin contraste IV."
  }
];

const ZONAS = [
  { id: "craneo", label: "Cráneo / Cuello", icon: "🧠" },
  { id: "torax", label: "Tórax / Cardíaco", icon: "🫁" },
  { id: "abdomen", label: "Abdomen / Pelvis", icon: "🫀" },
  { id: "columna", label: "Columna", icon: "🦴" },
  { id: "extremidades", label: "Extremidades", icon: "🦵" },
  { id: "corporal", label: "Corporal / Politrauma", icon: "🏥" }
];

window.PROTOCOLS = PROTOCOLS;
window.ZONAS = ZONAS;
